name: Deploy Content to sentinel-rg-dev [76e61ed1-bd6b-45b2-a9f3-7ac06e0fe5e4]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-76e61ed1-bd6b-45b2-a9f3-7ac06e0fe5e4.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'
#
# IMPORTANT: Path exclusions prevent infinite loops by excluding:
# - .sentinel/** (tracking files)
# - **/*.csv (CSV tracking files)
# - .github/workflows/** (workflow files)

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '!.sentinel/**'  # exclude sentinel tracking files to prevent loops
    - '!**/*.csv'  # exclude CSV files to prevent loops

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinel-ws-dev'
      workspaceName: 'sentinel-rg-dev'
      workspaceId: '660e617d-08fc-4554-9e7c-84f73a70c858'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,Parser,AutomationRule'
      branch: 'main'
      sourceControlId: '76e61ed1-bd6b-45b2-a9f3-7ac06e0fe5e4'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_76e61ed1bd6b45b2a9f37ac06e0fe5e4 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-76e61ed1-bd6b-45b2-a9f3-7ac06e0fe5e4.ps1